export interface QuizOption { label: string; value: string; icon?: string; }
export interface QuizReview { name: string; text: string; photoUrl: string; }
export interface QuizStep { step: number; question?: string; title?: string; subtitle?: string; subtext?: string; type: "hero" | "choice" | "testimonials_interstitial" | "loader" | "program_ready" | "lead_name" | "lead_contacts"; icon?: string; options?: QuizOption[]; points?: string[]; reviews?: QuizReview[]; cta?: string; meta?: string; pre_cta?: string; social_proof?: string; guarantee_text?: string; form?: { name_placeholder?: string; email_placeholder?: string; phone_placeholder?: string; cta?: string; }; }

export const quizData: QuizStep[] = [
  { step: 1, type: "hero", question: "Заговори англійською вільно — з JustSchool", subtext: "Наші студенти виходять на новий рівень та долають мовний бар'єр вже за перший місяць. Пройди тест, дізнайся свій рівень та отримай персональний план навчання.", social_proof: "🎓 Вибір 100 000+ студентів", pre_cta: "Лише 30 секунд, щоб дізнатися рівень:", cta: "Пройти тест", meta: "Безкоштовно та миттєво" },
  { step: 2, type: "choice", icon: "Target", question: "Яка ваша основна мета вивчення англійської?", options: [ { label: "Для роботи / кар'єри", value: "career", icon: "Briefcase" }, { label: "Для подорожей", value: "travel", icon: "Plane" }, { label: "Для переїзду за кордон", value: "relocation", icon: "Globe" }, { label: "Для саморозвитку / хобі", value: "hobby", icon: "Heart" }, { label: "Підготовка до іспитів (IELTS, TOEFL тощо)", value: "exams", icon: "BookOpen" } ] },
  { step: 3, type: "choice", icon: "BarChart3", question: "Який ваш поточний рівень знань?", options: [ { label: "Нульовий (не вчив/забув усе)", value: "zero", icon: "Battery" }, { label: "Початковий (знаю окремі слова)", value: "beginner", icon: "BatteryLow" }, { label: "Середній (можу трохи розмовляти)", value: "intermediate", icon: "BatteryMedium" }, { label: "Високий (вільно спілкуюся, хочу вдосконалити)", value: "high", icon: "BatteryFull" } ] },
  { step: 4, type: "testimonials_interstitial", icon: "Heart", title: "Наші студенти вже досягають своїх цілей", subtitle: "Подивіться, як наші студенти змінили своє життя з англійською:", reviews: [ { name: "Аліна", text: "JustSchool — це любов! За 2 місяці занять я подолала мовний бар'єр і успішно пройшла співбесіду.", photoUrl: "https://justschool.me/reviews/1123.jpg" }, { name: "Ігор", text: "Формат ідеально підійшов для мого щільного графіка. Дуже багато розмовної практики.", photoUrl: "https://justschool.me/reviews/2149064545.jpg" } ], cta: "Продовжити" },
  { step: 5, type: "choice", icon: "Zap", question: "Як часто ви готові займатися?", options: [ { label: "1-2 рази на тиждень", value: "low", icon: "Coffee" }, { label: "3 рази на тиждень", value: "medium", icon: "Zap" }, { label: "Кожен день (інтенсив)", value: "high", icon: "Rocket" } ] },
  { step: 6, type: "choice", icon: "LayoutGrid", question: "Який формат навчання вам найбільше підходить?", options: [ { label: "Індивідуально з викладачем", value: "solo", icon: "User" }, { label: "У невеликій групі", value: "group", icon: "Users" }, { label: "Ще не визначився(-лася)", value: "unsure", icon: "HelpCircle" } ] },
  { step: 7, type: "choice", icon: "Clock", question: "У який час вам зручніше проводити заняття?", options: [ { label: "Ранок (07:00 - 12:00)", value: "morning", icon: "Coffee" }, { label: "День (12:00 - 17:00)", value: "day", icon: "Timer" }, { label: "Вечір (17:00 - 22:00)", value: "evening", icon: "Moon" }, { label: "Вихідні дні", value: "weekend", icon: "Calendar" } ] },
  { step: 8, type: "loader", icon: "Wand2", title: "Обробляємо ваші дані...", points: [ "Аналізуємо вашу мету навчання", "Оцінюємо побажання щодо графіка", "Підбираємо найкращих викладачів", "Бронюємо місце на пробний урок" ] },
  { step: 9, type: "program_ready", icon: "Sparkles", title: "Ваша персональна стратегія готова!", subtitle: "Ми проаналізували ваші відповіді та склали оптимальний маршрут.", points: [ "Фокус на розмовній мові з першого уроку", "Доступ до інтерактивної платформи 24/7", "Підбір ментора під ваші цілі" ], cta: "Отримати програму" },
  { step: 10, type: "lead_name", icon: "User", title: "Раді знайомству! Як нам до тебе звертатися?", subtitle: "Скажи своє ім'я, щоб ми зробили твою стратегію персоналізованою.", form: { name_placeholder: "Твоє ім'я", cta: "Далі" } },
  { step: 11, type: "lead_contacts", icon: "Mail", title: "Твій персональний план готовий!", subtitle: "Залиш контакти, щоб отримати план та безкоштовний пробний урок.", guarantee_text: "Твої дані в безпеці.", form: { email_placeholder: "Твій e-mail", phone_placeholder: "Твій номер телефону", cta: "Отримати результат та урок" } },
];
