export interface QuizOption { label: string; value: string; icon?: string; }
export interface QuizReview { name: string; text: string; photoUrl: string; }
export interface QuizStep { step: number; question?: string; title?: string; subtitle?: string; subtext?: string; type: "hero" | "choice" | "testimonials_interstitial" | "loader" | "program_ready" | "lead_name" | "lead_contacts"; icon?: string; options?: QuizOption[]; points?: string[]; reviews?: QuizReview[]; cta?: string; meta?: string; pre_cta?: string; social_proof?: string; guarantee_text?: string; form?: { name_placeholder?: string; email_placeholder?: string; phone_placeholder?: string; cta?: string; }; }

export const quizData: QuizStep[] = [
  { step: 1, type: "hero", question: "Англійська для дітей, яку обожнюють", subtext: "Інтерактивне навчання в ігровій формі. Дізнайтеся рівень дитини та отримайте персональний план навчання для успішного майбутнього.", social_proof: "✨ 100 000+ задоволених батьків", pre_cta: "Дізнайтеся рівень дитини за 30 секунд:", cta: "Почати тест", meta: "Безкоштовно" },
  { step: 2, type: "choice", icon: "Cake", question: "Скільки років вашій дитині?", options: [ { label: "5-6 років", value: "5-6", icon: "Sunrise" }, { label: "7-10 років", value: "7-10", icon: "Sun" }, { label: "11-14 років", value: "11-14", icon: "Sunset" }, { label: "15-17 років", value: "15-17", icon: "Moon" } ] },
  { step: 3, type: "choice", icon: "Target", question: "Яка ваша основна мета?", options: [ { label: "Допомога зі школою", value: "school", icon: "BookOpen" }, { label: "Підготовка до іспитів / НМТ", value: "exams", icon: "Award" }, { label: "Вільне спілкування", value: "speaking", icon: "MessageSquare" }, { label: "Хобі та розвиток", value: "hobby", icon: "Heart" } ] },
  { step: 4, type: "choice", icon: "BarChart3", question: "Який рівень знань у дитини зараз?", options: [ { label: "Починає з нуля", value: "zero", icon: "Battery" }, { label: "Знає окремі слова", value: "beginner", icon: "BatteryLow" }, { label: "Може трохи розмовляти", value: "intermediate", icon: "BatteryMedium" }, { label: "Добре знає мову", value: "high", icon: "BatteryFull" } ] },
  { step: 5, type: "testimonials_interstitial", icon: "Heart", title: "Наші учні та їхні батьки задоволені", subtitle: "Ось що вони кажуть про навчання в JustSchool:", reviews: [ { name: "Олена (мама Максима)", text: "Син раніше не хотів вчити англійську, а тепер чекає кожного уроку! Платформа дуже цікава.", photoUrl: "https://justschool.me/reviews/1123.jpg" }, { name: "Дмитро (тато Анни)", text: "Помітний прогрес вже за перший місяць. Оцінки в школі покращилися.", photoUrl: "https://justschool.me/reviews/2149064545.jpg" } ], cta: "Продовжити" },
  { step: 6, type: "choice", icon: "LayoutGrid", question: "Який формат навчання ви розглядаєте?", options: [ { label: "Індивідуально з вчителем", value: "solo", icon: "User" }, { label: "У невеликій групі", value: "group", icon: "Users" }, { label: "Ще не визначилися", value: "unsure", icon: "HelpCircle" } ] },
  { step: 7, type: "choice", icon: "Clock", question: "У який час дитині зручніше займатися?", options: [ { label: "Ранок", value: "morning", icon: "Coffee" }, { label: "День", value: "day", icon: "Timer" }, { label: "Вечір", value: "evening", icon: "Moon" }, { label: "Вихідні дні", value: "weekend", icon: "Calendar" } ] },
  { step: 8, type: "loader", icon: "Wand2", title: "Аналізуємо відповіді дитини...", points: [ "Підбираємо програму під вік", "Враховуємо рівень знань", "Шукаємо найкращого вчителя", "Готуємо подарунок" ] },
  { step: 9, type: "program_ready", icon: "Sparkles", title: "Ідеальний план навчання готовий!", subtitle: "Ми підібрали найкращий шлях для вашої дитини.", points: [ "Ігрова форма навчання", "Персональний підхід", "Постійна підтримка викладача" ], cta: "Отримати план" },
  { step: 10, type: "lead_name", icon: "User", title: "Як звати дитину?", subtitle: "Ми підготуємо іменну програму навчання.", form: { name_placeholder: "Ім'я дитини", cta: "Далі" } },
  { step: 11, type: "lead_contacts", icon: "Mail", title: "Отримайте персональну стратегію!", subtitle: "Залиште свої контакти для зв'язку та безкоштовного уроку.", guarantee_text: "Ми дбаємо про вашу конфіденційність.", form: { email_placeholder: "Ваш e-mail", phone_placeholder: "Ваш номер телефону", cta: "Отримати план та урок" } },
];
